variable "aws_region" {}
variable "vpc_name" {}
variable "vpc_cidr" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "ec2_role_name" {}
variable "key-pair_name" {}
variable "folder_path" {}
variable "private_alb_name" {}
variable "public_alb_name" {}
variable "private_asg_name" {}
variable "private_launch-template_name" {}
variable "public_asg_name" {}
variable "public_launch-template_name" {}